# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8970b3db2cea247432eccb696fd413d7b6cd58b98e763d188c74c568aa969a79c13a075feb798249c2536e9135a47d340922ecbdc886e6e1c3bf812b6ba315b7

test:
  secret_key_base: 0c64d740291e90327c79745ee7899c5aa8a1791e3012ca9ea38d206deaf3eeadc7ea5379564d6276108bbfa5fc2b02936be5582695dc608ceb508c38fcefc4a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
